blank_issues_enabled: false
contact_links:
  - name: Questions â“
    url: https://github.com/matteozambon89/python-zero-spinner/discussions
    about: Ask questions or share ideas in Discussions
issue_templates:
  - name: ğŸ› Bug Report
    description: File a bug or unexpected behavior
    title: ğŸ› [BUG]
    labels: ['bug', 'needs-triage']
    body: ./ISSUE_TEMPLATE/bug_report.yml
  - name: ğŸš€ Feature Request
    description: Suggest a new feature or enhancement
    title: ğŸš€ [FEATURE]
    labels: ['enhancement', 'needs-triage']
    body: ./ISSUE_TEMPLATE/feature_request.yml
